### ISSUE TITLE
FOREACH within WRAPPER does not work properly

### ISSUE THREAD

**Issue by acidlemon** [lestrrat/go-xslate#17]
WRAPPERを呼んでいる呼び出し元でFOREACHを使うとループ変数が
正しく参照できず、nilになってしまうようです。
https://github.com/acidlemon/go-xslate/commit/b582d0742fafe3b9d9e7115f0ad864e2cac023d5

こちらでスタックマシンの状態を調べたところ、WRAPPERの中のFOREACHの場合、
ForeachNodeのIndexVarIdxが0ではなく1となります。

しかし、ForeachNode.ListNode内のループ変数を参照するLocalVarNodeのOffsetの値が0と
なっており、vmのtxLoadLvarでTXOPLoadLvarのArgIntの値がそのまま0となっていて
スタックからLvarを引いてくるオフセットがずれているようでした。

parser/builder.goで直すにせよvm/ops.goで直すにせよ、ちょっと直し方がよくわかりませんでした。
ご確認いただけますか?

**Comment by lestrrat** [comment]
このissueの存在今気づいた…
